stages:
  - test
  - build

variables:
  CHECKOUT: registry.gitlab.com/lucafmarques/hash-test

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/

checkout_test:
  stage: test
  image: golang:1.16
  extends: .go-cache
  except:
    - tags
  script:
    - make coverage
  
checkout_build:
  stage: build
  image: docker:stable
  only:
    - tags
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
  script:
    - docker build -t $CHECKOUT:$CI_COMMIT_TAG -f dockerfile checkout
    - docker push $CHECKOUT:$CI_COMMIT_TAG