stages:
  - test
  - build

variables:
  CHECKOUT: registry.gitlab.com/lucafmarques/hash-tech-challenge

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/

checkout_test:
  stage: test
  image: golang:1.16
  extends: .go-cache
  except:
    - tags
  script:
    - make coverage
  
checkout_build:
  stage: build
  image: docker:stable
  only:
    - tags
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CHECKOUT:$CI_COMMIT_TAG -f dockerfile .
    - docker push $CHECKOUT:$CI_COMMIT_TAG