server:
  host: localhost:8080
  timeout: 10
  discount_host: discount:8080

discount_service:
  insecure: true
  cert_path: "../credentials/localhost.crt"
  key_path: "../credentials/localhost.key"

rules:
  black_friday_date: 25/11
