version: "3.9"
services:
  discount:
    image: hashorg/hash-mock-discount-service
    ports:
      - "50051:50051"
  checkout:
    build: .
    ports: 
      - "8080:8080"
    environment: 
      API_KEYS: "b6346fc6-a385-4c93-aa98-8c50eac12974"
      BLACK_FRIDAY_DATE: "2021-08-07"