version: "3.9"
services:
  discount:
    image: hashorg/hash-mock-discount-service
    ports:
      - "50051:50051"
  checkout:
    build: .
    ports: 
      - "8080:8080"
    environment: 
      API_KEYS: "TEST,TESTA"